apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clouds-api
  name: clouds-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clouds-api
  template:
    metadata:
      labels:
        app: clouds-api
    spec:
      containers:
#        - image: image-registry.openshift-image-registry.svc:5000/clouds-build/clouds-api:latest
        - image: default-route-openshift-image-registry.apps.qmcm57yune3f2c5cce.eastus.aroapp.io/clouds-build/clouds-api:latest
          imagePullPolicy: Always
          name: clouds-api
          ports:
            - containerPort: 8080
              protocol: TCP
